// Demo launcher — starts the real application in a sealed sandbox.
//
//   npm run demo            start it
//   npm run demo -- --reset start it with an empty demo diary
//
// This is the ordinary server (backend/server.js, the same code the client
// will get), with four things pinned before any of it loads:
//
//   1. Appointments go to demo/appointments.demo.json, never to the real
//      backend/data/appointments.json.
//   2. DATABASE_URL is blanked, so a production Postgres string sitting in
//      backend/.env cannot be reached even by accident.
//   3. ADMIN_KEY is the demo key from .env.demo, not the clinic's real one.
//   4. SMTP is blanked, so nothing can be emailed to the clinic or anyone
//      else while presenting.
//
// The order matters. dotenv does not overwrite variables that are already
// set, so assigning these here — before backend/server.js runs its own
// dotenv.config() — is what makes them stick.

const path = require("path");
const fs = require("fs");
const crypto = require("crypto");

const ROOT = path.join(__dirname, "..");
const DEMO_DIR = path.join(ROOT, "demo");
const DEMO_DB = path.join(DEMO_DIR, "appointments.demo.json");
const DEMO_ENV = path.join(ROOT, ".env.demo");

fs.mkdirSync(DEMO_DIR, { recursive: true });

// ---------------------------------------------------------------------------
// The demo admin key
// ---------------------------------------------------------------------------
// Generated once into .env.demo (git-ignored) and reused on every later run,
// so the key you rehearse with is the key you present with. It is never
// printed here: the file is the only place it exists.

function readDemoKey() {
  if (!fs.existsSync(DEMO_ENV)) return "";
  const m = /^ADMIN_KEY=(.*)$/m.exec(fs.readFileSync(DEMO_ENV, "utf8"));
  return m ? m[1].trim() : "";
}

let demoKey = readDemoKey();
let keyIsNew = false;
if (!demoKey) {
  demoKey = "demo-" + crypto.randomBytes(18).toString("base64url");
  fs.writeFileSync(
    DEMO_ENV,
    [
      "# Demo credentials — git-ignored, local only, safe to delete.",
      "# Generated by scripts/demo.js. Delete this file to get a new key.",
      "#",
      "# This key unlocks ONLY the demo diary in demo/appointments.demo.json",
      "# on this machine. It is not the clinic's admin key and grants no",
      "# access to the live site.",
      "ADMIN_KEY=" + demoKey,
      "",
    ].join("\n")
  );
  keyIsNew = true;
}

// ---------------------------------------------------------------------------
// Seal the environment
// ---------------------------------------------------------------------------

if (process.argv.includes("--reset") && fs.existsSync(DEMO_DB)) {
  fs.unlinkSync(DEMO_DB);
}
if (!fs.existsSync(DEMO_DB)) fs.writeFileSync(DEMO_DB, "[]");

process.env.APPOINTMENTS_FILE = DEMO_DB;

// Blank rather than delete: dotenv skips keys that are already present, so an
// empty string here beats whatever backend/.env holds. db.js treats "" as
// "no database" and uses the file driver.
process.env.DATABASE_URL = "";
process.env.POSTGRES_URL = "";

process.env.ADMIN_KEY = demoKey;

// mailer.js refuses to send unless BOTH SMTP_HOST and CLINIC_EMAIL are set.
// Blanking all four means no message can leave this machine.
process.env.SMTP_HOST = "";
process.env.SMTP_USER = "";
process.env.SMTP_PASS = "";
process.env.CLINIC_EMAIL = "";
process.env.FROM_EMAIL = "";

process.env.PORT = process.env.DEMO_PORT || "5500";

// The AI provider keys are deliberately left alone: if one is configured, the
// assistant should work in the demo exactly as it will for the client.

const port = process.env.PORT;

console.log("");
console.log("  BRIGHT SMILE — DEMO MODE");
console.log("  " + "-".repeat(52));
console.log("  Diary:     demo/appointments.demo.json (isolated)");
console.log("  Real data: backend/data/appointments.json — untouched");
console.log("  Database:  production Postgres unreachable (DATABASE_URL blanked)");
console.log("  Email:     disabled — nothing can be sent");
console.log("  Admin key: in .env.demo" + (keyIsNew ? "  (just generated)" : ""));
console.log("  " + "-".repeat(52));
console.log("  Website:   http://localhost:" + port + "/");
console.log("  Dashboard: http://localhost:" + port + "/admin");
console.log("");

process.on("uncaughtException", (err) => {
  if (err && err.code === "EADDRINUSE") {
    console.error(
      `Port ${port} is already in use — another copy of the site is probably running.\n` +
        `Stop it, or start the demo on a different port:  DEMO_PORT=5501 npm run demo`
    );
    process.exit(1);
  }
  throw err;
});

require(path.join(ROOT, "backend", "server.js"));
